import { Player, Team } from "./types";

export const TEAMS: Team[] = [
  {
    id: "t1",
    name: "Azure Knights",
    abbr: "AZK",
    primaryColor: "#3b82f6",
    secondaryColor: "#1e3a8a",
    badgeUrl: "",
  },
  {
    id: "t2",
    name: "Crimson Fury",
    abbr: "CRF",
    primaryColor: "#ef4444",
    secondaryColor: "#7f1d1d",
    badgeUrl: "",
  },
  {
    id: "t3",
    name: "Emerald Vipers",
    abbr: "EMV",
    primaryColor: "#10b981",
    secondaryColor: "#064e3b",
    badgeUrl: "",
  },
  {
    id: "t4",
    name: "Golden Lions",
    abbr: "GDL",
    primaryColor: "#eab308",
    secondaryColor: "#713f12",
    badgeUrl: "",
  },
  {
    id: "t5",
    name: "Neon Shadows",
    abbr: "NSH",
    primaryColor: "#a855f7",
    secondaryColor: "#4c1d95",
    badgeUrl: "",
  },
  {
    id: "t6",
    name: "Frost Giants",
    abbr: "FGT",
    primaryColor: "#06b6d4",
    secondaryColor: "#164e63",
    badgeUrl: "",
  },
  {
    id: "t7",
    name: "Silver Falcons",
    abbr: "SLF",
    primaryColor: "#94a3b8",
    secondaryColor: "#1e293b",
    badgeUrl: "",
  },
  {
    id: "t8",
    name: "Ruby Rockets",
    abbr: "RBR",
    primaryColor: "#f43f5e",
    secondaryColor: "#881337",
    badgeUrl: "",
  },
  {
    id: "t9",
    name: "Cyber Sharks",
    abbr: "CBS",
    primaryColor: "#14b8a6",
    secondaryColor: "#134e4a",
    badgeUrl: "",
  },
  {
    id: "t10",
    name: "Mystic Phoenix",
    abbr: "MYP",
    primaryColor: "#f97316",
    secondaryColor: "#7c2d12",
    badgeUrl: "",
  },
  {
    id: "t11",
    name: "Midnight Ravens",
    abbr: "MRV",
    primaryColor: "#6366f1",
    secondaryColor: "#312e81",
    badgeUrl: "",
  },
  {
    id: "t12",
    name: "Jungle Strikers",
    abbr: "JST",
    primaryColor: "#84cc16",
    secondaryColor: "#365314",
    badgeUrl: "",
  },
];

export const DEMO_PLAYERS: Player[] = [
  {
    id: "p1",
    name: "Ironhand",
    position: "GK",
    rating: 75,
    rarity: "COMMON",
    isNft: false,
    color: "#9ca3af",
    speed: 55,
    shooting: 40,
    passing: 65,
    defending: 80,
  },
  {
    id: "p2",
    name: "Stone",
    position: "DEF",
    rating: 72,
    rarity: "COMMON",
    isNft: false,
    color: "#9ca3af",
    speed: 65,
    shooting: 45,
    passing: 60,
    defending: 78,
  },
  {
    id: "p3",
    name: "Wall",
    position: "DEF",
    rating: 70,
    rarity: "COMMON",
    isNft: false,
    color: "#9ca3af",
    speed: 60,
    shooting: 40,
    passing: 55,
    defending: 75,
  },
  {
    id: "p4",
    name: "Spark",
    position: "MID",
    rating: 76,
    rarity: "COMMON",
    isNft: false,
    color: "#9ca3af",
    speed: 72,
    shooting: 65,
    passing: 78,
    defending: 60,
  },
  {
    id: "p5",
    name: "Engine",
    position: "MID",
    rating: 78,
    rarity: "COMMON",
    isNft: false,
    color: "#9ca3af",
    speed: 75,
    shooting: 70,
    passing: 80,
    defending: 65,
  },
  {
    id: "p6",
    name: "Strike",
    position: "ATT",
    rating: 74,
    rarity: "COMMON",
    isNft: false,
    color: "#9ca3af",
    speed: 78,
    shooting: 76,
    passing: 60,
    defending: 35,
  },
  {
    id: "p7",
    name: "Bolt",
    position: "ATT",
    rating: 79,
    rarity: "COMMON",
    isNft: false,
    color: "#9ca3af",
    speed: 85,
    shooting: 80,
    passing: 65,
    defending: 30,
  },
];

export const EXTRA_PLAYERS: Player[] = [
  {
    id: "p8",
    name: "Shadow",
    position: "ATT",
    rating: 81,
    rarity: "RARE",
    isNft: false,
    color: "#a855f7",
    speed: 88,
    shooting: 82,
    passing: 70,
    defending: 35,
  },
  {
    id: "p9",
    name: "Glint",
    position: "MID",
    rating: 79,
    rarity: "RARE",
    isNft: false,
    color: "#34d399",
    speed: 80,
    shooting: 72,
    passing: 85,
    defending: 68,
  },
  {
    id: "p10",
    name: "Vortex",
    position: "DEF",
    rating: 83,
    rarity: "EPIC",
    isNft: false,
    color: "#f472b6",
    speed: 75,
    shooting: 50,
    passing: 72,
    defending: 88,
  },
];

export const NFT_REWARDS: Player[] = [
  {
    id: "nft1",
    name: "Titan",
    position: "DEF",
    rating: 88,
    rarity: "EPIC",
    isNft: true,
    color: "#a855f7",
    speed: 78,
    shooting: 55,
    passing: 75,
    defending: 92,
  },
  {
    id: "nft2",
    name: "Phoenix",
    position: "ATT",
    rating: 92,
    rarity: "LEGENDARY",
    isNft: true,
    color: "#f59e0b",
    speed: 93,
    shooting: 95,
    passing: 85,
    defending: 40,
  },
];
